### ISSUE TITLE
reporte y practica 

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-MLR062998#2]
[practica_Dll.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-MLR062998/files/6382578/practica_Dll.pdf)

[calculadora.zip](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-MLR062998/files/6382590/calculadora.zip)

**Comment by CxrlosMX** [comment]
Calificación obtenida: 20/20.

**Comment by josealfredo79** [comment]
Falta subir al repositorio el codigo

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
